name: Tests
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pipenv
            pipenv install --dev
        - run: pipenv run pytest
        - uses: actions/upload-artifact@v1
          with:
            name: pytest-results-${{ matrix.python-version }}
            path: htmlcov
          # Use always() to always run this step to publish test results when there are test failures
          if: ${{ always() }}
